import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { format } from 'date-fns';
import { CalendarDays, Mail, MessageSquare, Phone, Plus, Search, Users } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useToast } from '@/hooks/use-toast';
import { crmApi, jsonRequest } from './api';
import { useCRM } from './CRMWorkspace';
import type { CRMActivity, CRMContact } from './types';

const activityTypes = ['all', 'note', 'call', 'email', 'whatsapp', 'meeting', 'follow_up'] as const;
const icons: Record<string, typeof Phone> = { call: Phone, email: Mail, whatsapp: MessageSquare, meeting: Users, follow_up: CalendarDays, note: MessageSquare };

export default function ActivitiesPage() {
  const { can } = useCRM();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [type, setType] = useState<(typeof activityTypes)[number]>('all');
  const [search, setSearch] = useState('');
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ contactId: '', type: 'call', title: '', description: '', outcome: '', nextFollowUp: '', createTask: true });
  const query = useQuery({ queryKey: ['crm-activities', type], queryFn: () => crmApi<{ activities: CRMActivity[] }>(`/activities${type === 'all' ? '' : `?type=${type}`}`) });
  const contactsQuery = useQuery({ queryKey: ['crm-activity-contacts'], queryFn: () => crmApi<{ contacts: CRMContact[] }>('/contacts?pageSize=200&sortBy=updated_at&sortDirection=desc') });
  const activities = useMemo(() => (query.data?.activities || []).filter((activity) => !search || `${activity.title} ${activity.description || ''} ${activity.contact?.name || ''}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]);
  const create = useMutation({ mutationFn: () => crmApi(`/contacts/${form.contactId}/activities`, jsonRequest('POST', { ...form, nextFollowUp: form.nextFollowUp ? new Date(form.nextFollowUp).toISOString() : undefined })), onSuccess: () => { toast({ title: 'Activity logged' }); setOpen(false); setForm({ contactId: '', type: 'call', title: '', description: '', outcome: '', nextFollowUp: '', createTask: true }); void query.refetch(); void queryClient.invalidateQueries({ queryKey: ['crm-dashboard'] }); }, onError: (error: Error) => toast({ title: 'Could not log activity', description: error.message, variant: 'destructive' }) });

  return <div className="space-y-5 p-4 sm:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Dynamic Activity</h2><p className="text-sm text-slate-500">Calls, meetings, messages, notes, and scheduled follow-ups.</p></div>{can('update_leads') && <button onClick={() => setOpen(true)} className="flex h-9 items-center gap-2 bg-blue-600 px-4 text-sm font-medium text-white"><Plus className="h-4 w-4" />Log Activity</button>}</div>
    <div className="border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">
      <div className="flex flex-wrap gap-2 border-b border-slate-200 p-3 dark:border-slate-800"><div className="relative min-w-56 flex-1 sm:max-w-sm"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="h-9 w-full border border-slate-300 pl-9 pr-3 text-sm" placeholder="Search activity or lead" /></div><select value={type} onChange={(event) => setType(event.target.value as typeof type)} className="h-9 border border-slate-300 bg-white px-3 text-sm"><option value="all">All Activity Types</option>{activityTypes.slice(1).map((item) => <option key={item} value={item}>{item.replace('_', ' ')}</option>)}</select></div>
      <div className="divide-y divide-slate-100 dark:divide-slate-800">{query.isLoading ? <p className="p-10 text-center text-sm text-slate-500">Loading activity...</p> : activities.length ? activities.map((activity) => { const Icon = icons[activity.type] || MessageSquare; return <article key={activity.id} className="flex gap-4 p-4 hover:bg-slate-50 dark:hover:bg-slate-800/50"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-blue-50 text-blue-600"><Icon className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{activity.title}</p><p className="text-sm text-blue-700">{activity.contact?.name || 'Unknown lead'}</p></div><time className="text-xs text-slate-400">{format(new Date(activity.created_at), 'dd MMM yyyy, hh:mm a')}</time></div>{activity.description && <p className="mt-2 whitespace-pre-wrap text-sm text-slate-600 dark:text-slate-300">{activity.description}</p>}<div className="mt-2 flex flex-wrap gap-x-4 text-xs text-slate-500"><span className="capitalize">{activity.type.replace('_', ' ')}</span>{activity.outcome && <span>Outcome: {activity.outcome}</span>}<span>By {activity.created_by || activity.actor?.full_name || activity.actor?.email || 'System'}</span></div></div></article>; }) : <p className="p-10 text-center text-sm text-slate-500">No activities found.</p>}</div>
    </div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Log Activity</DialogTitle><DialogDescription>Record an interaction and optionally schedule the next follow-up.</DialogDescription></DialogHeader><form onSubmit={(event) => { event.preventDefault(); create.mutate(); }} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Lead<select required value={form.contactId} onChange={(event) => setForm((value) => ({ ...value, contactId: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 bg-white px-2"><option value="">Select lead</option>{contactsQuery.data?.contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.name} - {contact.mobile}</option>)}</select></label><label className="text-sm font-medium">Activity Type<select value={form.type} onChange={(event) => setForm((value) => ({ ...value, type: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 bg-white px-2">{activityTypes.slice(1).map((item) => <option key={item} value={item}>{item.replace('_', ' ')}</option>)}</select></label><label className="text-sm font-medium">Subject<input required value={form.title} onChange={(event) => setForm((value) => ({ ...value, title: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 px-3" /></label><label className="text-sm font-medium sm:col-span-2">Details<textarea value={form.description} onChange={(event) => setForm((value) => ({ ...value, description: event.target.value }))} className="mt-1 min-h-24 w-full border border-slate-300 p-3" /></label><label className="text-sm font-medium">Outcome<input value={form.outcome} onChange={(event) => setForm((value) => ({ ...value, outcome: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 px-3" /></label><label className="text-sm font-medium">Next Follow-up<input type="datetime-local" value={form.nextFollowUp} onChange={(event) => setForm((value) => ({ ...value, nextFollowUp: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 px-3" /></label>{form.nextFollowUp && <label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={form.createTask} onChange={(event) => setForm((value) => ({ ...value, createTask: event.target.checked }))} />Create a follow-up task</label>}<div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setOpen(false)} className="h-9 border border-slate-300 px-4 text-sm">Cancel</button><button disabled={create.isPending} className="h-9 bg-blue-600 px-4 text-sm font-medium text-white">Log Activity</button></div></form></DialogContent></Dialog>
  </div>;
}
