import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { format, isBefore, isToday } from 'date-fns';
import { CalendarClock, Check, Clock3, Plus, Search, Trash2 } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { crmApi, jsonRequest } from './api';
import { useCRM } from './CRMWorkspace';
import type { CRMContact, CRMTask } from './types';

export default function TasksPage() {
  const { meta } = useCRM();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [filter, setFilter] = useState<'pending' | 'completed' | 'all'>('pending');
  const [search, setSearch] = useState('');
  const [addOpen, setAddOpen] = useState(false);
  const [form, setForm] = useState({ title: '', description: '', priority: 'medium', dueAt: '', contactId: '', assigneeId: meta.actor.id });
  const tasksQuery = useQuery({ queryKey: ['crm-tasks', filter], queryFn: () => crmApi<{ tasks: CRMTask[] }>(`/tasks?status=${filter}`) });
  const contactsQuery = useQuery({ queryKey: ['crm-task-contacts'], queryFn: () => crmApi<{ contacts: CRMContact[] }>('/contacts?pageSize=200&sortBy=name&sortDirection=asc') });
  const tasks = useMemo(() => tasksQuery.data?.tasks || [], [tasksQuery.data?.tasks]);
  const filtered = useMemo(() => tasks.filter((task) => !search || `${task.title} ${task.contact?.name || ''} ${task.assignee?.full_name || ''}`.toLowerCase().includes(search.toLowerCase())), [tasks, search]);
  const now = new Date();
  const stats = { total: tasks.length, today: tasks.filter((task) => task.due_at && isToday(new Date(task.due_at))).length, overdue: tasks.filter((task) => task.status !== 'completed' && task.due_at && isBefore(new Date(task.due_at), now)).length, completed: tasks.filter((task) => task.status === 'completed').length };
  const statItems = [
    { label: 'Total Tasks', value: stats.total, icon: Clock3 },
    { label: 'Due Today', value: stats.today, icon: CalendarClock },
    { label: 'Overdue', value: stats.overdue, icon: Clock3 },
    { label: 'Completed', value: stats.completed, icon: Check },
  ];
  const refresh = () => { void tasksQuery.refetch(); void queryClient.invalidateQueries({ queryKey: ['crm-dashboard'] }); };
  const create = useMutation({ mutationFn: () => crmApi('/tasks', jsonRequest('POST', { ...form, contactId: form.contactId || null, assigneeId: form.assigneeId || null, dueAt: new Date(form.dueAt).toISOString() })), onSuccess: () => { toast({ title: 'Task created' }); setAddOpen(false); setForm({ title: '', description: '', priority: 'medium', dueAt: '', contactId: '', assigneeId: meta.actor.id }); refresh(); }, onError: (error: Error) => toast({ title: 'Could not create task', description: error.message, variant: 'destructive' }) });
  const update = useMutation({ mutationFn: ({ id, body }: { id: string; body: unknown }) => crmApi(`/tasks/${id}`, jsonRequest('PATCH', body)), onSuccess: refresh, onError: (error: Error) => toast({ title: 'Task update failed', description: error.message, variant: 'destructive' }) });
  const remove = useMutation({ mutationFn: (id: string) => crmApi(`/tasks/${id}`, jsonRequest('DELETE')), onSuccess: () => { toast({ title: 'Task deleted' }); refresh(); }, onError: (error: Error) => toast({ title: 'Could not delete task', description: error.message, variant: 'destructive' }) });

  return <div className="space-y-5 p-4 sm:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Calendar & Tasks</h2><p className="text-sm text-slate-500">Manage counsellor follow-ups and deadlines.</p></div><button onClick={() => setAddOpen(true)} className="flex h-9 items-center gap-2 bg-blue-600 px-4 text-sm font-medium text-white"><Plus className="h-4 w-4" />Add Task</button></div>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{statItems.map((item) => <div key={item.label} className="flex items-center gap-3 border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><item.icon className="h-5 w-5 text-blue-600" /><div><p className="text-2xl font-semibold">{item.value}</p><p className="text-xs text-slate-500">{item.label}</p></div></div>)}</section>
    <div className="border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">
      <div className="flex flex-wrap items-center gap-3 border-b border-slate-200 p-3 dark:border-slate-800"><div className="flex gap-1">{(['pending', 'completed', 'all'] as const).map((item) => <button key={item} onClick={() => setFilter(item)} className={cn('h-8 px-3 text-sm capitalize', filter === item ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-600 dark:bg-slate-800')}>{item}</button>)}</div><div className="relative min-w-56 flex-1 sm:max-w-sm"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="h-9 w-full border border-slate-300 pl-9 pr-3 text-sm" placeholder="Search tasks or leads" /></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-100 text-left text-xs uppercase text-slate-500 dark:bg-slate-800"><tr><th className="px-4 py-3">Status</th><th className="px-4 py-3">Task</th><th className="px-4 py-3">Lead</th><th className="px-4 py-3">Owner</th><th className="px-4 py-3">Due</th><th className="px-4 py-3">Priority</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.length ? filtered.map((task) => { const overdue = task.status !== 'completed' && task.due_at && isBefore(new Date(task.due_at), new Date()); return <tr key={task.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50"><td className="px-4 py-3"><button onClick={() => update.mutate({ id: task.id, body: { status: task.status === 'completed' ? 'pending' : 'completed' } })} className={cn('grid h-6 w-6 place-items-center rounded-full border', task.status === 'completed' ? 'border-emerald-600 bg-emerald-600 text-white' : 'border-slate-300')} aria-label={`${task.status === 'completed' ? 'Reopen' : 'Complete'} ${task.title}`}>{task.status === 'completed' && <Check className="h-4 w-4" />}</button></td><td className="px-4 py-3"><p className={cn('font-medium', task.status === 'completed' && 'text-slate-400 line-through')}>{task.title}</p><p className="max-w-sm truncate text-xs text-slate-500">{task.description || 'No description'}</p></td><td className="px-4 py-3">{task.contact?.name || 'General'}</td><td className="px-4 py-3">{task.assignee?.full_name || task.assignee?.email || task.assigned_to || '-'}</td><td className={cn('whitespace-nowrap px-4 py-3', overdue && 'font-medium text-red-600')}>{task.due_at ? format(new Date(task.due_at), 'dd MMM yyyy, hh:mm a') : '-'}</td><td className="px-4 py-3"><span className={cn('px-2 py-1 text-xs capitalize', task.priority === 'urgent' || task.priority === 'high' ? 'bg-red-50 text-red-700' : 'bg-slate-100 text-slate-600')}>{task.priority}</span></td><td className="px-4 py-3"><button onClick={() => { if (window.confirm(`Delete task "${task.title}"?`)) remove.mutate(task.id); }} className="text-slate-400 hover:text-red-600" aria-label={`Delete ${task.title}`}><Trash2 className="h-4 w-4" /></button></td></tr>; }) : <tr><td colSpan={7} className="p-10 text-center text-slate-500">No tasks found.</td></tr>}</tbody></table></div>
    </div>
    <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Add Task</DialogTitle><DialogDescription>Schedule a lead follow-up or internal task.</DialogDescription></DialogHeader><form onSubmit={(event) => { event.preventDefault(); create.mutate(); }} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Task Title<input required value={form.title} onChange={(event) => setForm((value) => ({ ...value, title: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 px-3" /></label><label className="text-sm font-medium sm:col-span-2">Description<textarea value={form.description} onChange={(event) => setForm((value) => ({ ...value, description: event.target.value }))} className="mt-1 min-h-20 w-full border border-slate-300 p-3" /></label><label className="text-sm font-medium">Lead<select value={form.contactId} onChange={(event) => setForm((value) => ({ ...value, contactId: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 bg-white px-2"><option value="">General task</option>{contactsQuery.data?.contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.name} - {contact.mobile}</option>)}</select></label><label className="text-sm font-medium">Assigned To<select value={form.assigneeId} onChange={(event) => setForm((value) => ({ ...value, assigneeId: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 bg-white px-2">{meta.users.map((user) => <option key={user.id} value={user.id}>{user.full_name || user.email}</option>)}</select></label><label className="text-sm font-medium">Due Date & Time<input required type="datetime-local" value={form.dueAt} onChange={(event) => setForm((value) => ({ ...value, dueAt: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 px-3" /></label><label className="text-sm font-medium">Priority<select value={form.priority} onChange={(event) => setForm((value) => ({ ...value, priority: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 bg-white px-2"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setAddOpen(false)} className="h-9 border border-slate-300 px-4 text-sm">Cancel</button><button disabled={create.isPending} className="h-9 bg-blue-600 px-4 text-sm font-medium text-white">Create Task</button></div></form></DialogContent></Dialog>
  </div>;
}
