import { useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { format } from 'date-fns';
import { KeyRound, Plus, Search, ShieldCheck, UserCheck, UserCog, UserX } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { crmApi, jsonRequest } from './api';
import { useCRM } from './CRMWorkspace';
import type { CRMRole, CRMUser } from './types';

const roles: Array<{ value: CRMRole; label: string }> = [
  { value: 'counsellor', label: 'Counsellor' }, { value: 'team_lead', label: 'Team Lead' },
  { value: 'admin', label: 'Administrator' }, { value: 'super_admin', label: 'Super Admin' },
];
const permissions = [
  ['view_leads', 'View leads'], ['add_leads', 'Add quick leads'], ['update_leads', 'Update lead details'],
  ['assign_leads', 'Assign and reassign leads'], ['delete_leads', 'Delete leads'], ['import_leads', 'Upload bulk leads'], ['download_leads', 'Download leads'],
  ['manage_tasks', 'Manage tasks and follow-ups'], ['view_reports', 'View reports and analytics'],
  ['manage_users', 'Manage users'], ['manage_settings', 'Manage CRM settings'],
] as const;
const emptyForm = { fullName: '', email: '', role: 'counsellor' as CRMRole, teamId: '', password: '', permissions: ['view_leads', 'add_leads', 'update_leads', 'manage_tasks'] as string[] };

export default function UsersPage() {
  const { meta, refreshMeta } = useCRM();
  const { toast } = useToast();
  const [tab, setTab] = useState<'active' | 'inactive'>('active');
  const [search, setSearch] = useState('');
  const [createOpen, setCreateOpen] = useState(false);
  const [editUser, setEditUser] = useState<CRMUser | null>(null);
  const [form, setForm] = useState(emptyForm);
  const [generatedPassword, setGeneratedPassword] = useState('');
  const usersQuery = useQuery({ queryKey: ['crm-users'], queryFn: () => crmApi<{ users: CRMUser[] }>('/users') });
  const users = useMemo(() => (usersQuery.data?.users || []).filter((user) => Boolean(user.is_active) === (tab === 'active') && (!search || `${user.full_name || ''} ${user.email} ${user.role} ${user.crm_team?.name || ''}`.toLowerCase().includes(search.toLowerCase()))), [usersQuery.data, tab, search]);
  const refresh = () => { void usersQuery.refetch(); void refreshMeta(); };
  const create = useMutation({ mutationFn: () => crmApi<{ generatedPassword?: string }>('/users', jsonRequest('POST', { ...form, teamId: form.teamId || null, password: form.password || undefined })), onSuccess: (result) => { toast({ title: 'User created successfully' }); setGeneratedPassword(result.generatedPassword || ''); if (!result.generatedPassword) { setCreateOpen(false); setForm(emptyForm); } refresh(); }, onError: (error: Error) => toast({ title: 'Could not create user', description: error.message, variant: 'destructive' }) });
  const update = useMutation({ mutationFn: (body: unknown) => crmApi(`/users/${editUser?.id}`, jsonRequest('PATCH', body)), onSuccess: () => { toast({ title: 'User updated' }); setEditUser(null); refresh(); }, onError: (error: Error) => toast({ title: 'Could not update user', description: error.message, variant: 'destructive' }) });

  const openEdit = (user: CRMUser) => { setEditUser(user); setForm({ fullName: user.full_name || '', email: user.email, role: user.role, teamId: user.team_id || '', password: '', permissions: user.permissions || [] }); };
  return <div className="space-y-5 p-4 sm:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Manage Users</h2><p className="text-sm text-slate-500">Create accounts, assign roles and teams, and control CRM permissions.</p></div><button onClick={() => { setGeneratedPassword(''); setForm(emptyForm); setCreateOpen(true); }} className="flex h-9 items-center gap-2 bg-blue-600 px-4 text-sm font-medium text-white"><Plus className="h-4 w-4" />Create User</button></div>
    <section className="grid gap-3 sm:grid-cols-3">{[
      { label: 'Active Users', value: (usersQuery.data?.users || []).filter((user) => user.is_active).length, icon: UserCheck },
      { label: 'Inactive Users', value: (usersQuery.data?.users || []).filter((user) => !user.is_active).length, icon: UserX },
      { label: 'Administrators', value: (usersQuery.data?.users || []).filter((user) => ['admin', 'super_admin'].includes(user.role)).length, icon: ShieldCheck },
    ].map((item) => <div key={item.label} className="flex items-center gap-3 border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><item.icon className="h-5 w-5 text-blue-600" /><div><p className="text-2xl font-semibold">{item.value}</p><p className="text-xs text-slate-500">{item.label}</p></div></div>)}</section>
    <div className="border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">
      <div className="flex flex-wrap items-center gap-3 border-b border-slate-200 p-3 dark:border-slate-800"><div className="flex">{(['active', 'inactive'] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={cn('h-9 border-b-2 px-4 text-sm capitalize', tab === item ? 'border-blue-600 font-medium text-blue-600' : 'border-transparent text-slate-500')}>{item} ({(usersQuery.data?.users || []).filter((user) => Boolean(user.is_active) === (item === 'active')).length})</button>)}</div><div className="relative ml-auto min-w-56 sm:max-w-sm"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="h-9 w-full border border-slate-300 pl-9 pr-3 text-sm" placeholder="Search users" /></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[#e8edf2] text-left text-xs uppercase text-slate-600"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Email ID</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Permission</th><th className="px-4 py-3">Team</th><th className="px-4 py-3">Last Login</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{usersQuery.isLoading ? <tr><td colSpan={7} className="p-10 text-center text-slate-500">Loading users...</td></tr> : users.length ? users.map((user) => <tr key={user.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50"><td className="px-4 py-3 font-medium text-blue-700">{user.full_name || '-'}</td><td className="px-4 py-3">{user.email}</td><td className="px-4 py-3"><span className="flex items-center gap-1.5 capitalize"><UserCog className="h-4 w-4 text-slate-400" />{user.role.replace('_', ' ')}</span></td><td className="px-4 py-3"><span className="text-blue-700">{['admin', 'super_admin'].includes(user.role) ? 'Full access' : `${user.permissions?.length || 0} permissions`}</span></td><td className="px-4 py-3">{user.crm_team?.name || user.team || '-'}</td><td className="px-4 py-3">{user.last_sign_in_at ? format(new Date(user.last_sign_in_at), 'dd/MM/yyyy hh:mm a') : 'Never'}</td><td className="px-4 py-3 text-right"><button onClick={() => openEdit(user)} className="h-8 border border-slate-300 px-3 text-xs font-medium">Manage</button></td></tr>) : <tr><td colSpan={7} className="p-10 text-center text-slate-500">No users found.</td></tr>}</tbody></table></div>
    </div>

    <Dialog open={createOpen} onOpenChange={(open) => { setCreateOpen(open); if (!open) setGeneratedPassword(''); }}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Create User</DialogTitle><DialogDescription>Create a login, assign a role, team, and explicit CRM permissions.</DialogDescription></DialogHeader>{generatedPassword ? <div className="border border-emerald-300 bg-emerald-50 p-5"><h3 className="font-semibold text-emerald-900">User created</h3><p className="mt-2 text-sm text-emerald-800">Share this temporary password securely. It is shown only once.</p><div className="mt-3 flex items-center gap-2 border border-emerald-300 bg-white p-3 font-mono text-sm"><KeyRound className="h-4 w-4" /><span className="break-all">{generatedPassword}</span></div><button onClick={() => { setCreateOpen(false); setGeneratedPassword(''); setForm(emptyForm); }} className="mt-4 h-9 bg-emerald-700 px-4 text-sm font-medium text-white">Done</button></div> : <UserForm form={form} setForm={setForm} teams={meta.teams} submitLabel="Create User" submitting={create.isPending} onSubmit={() => create.mutate()} />}</DialogContent></Dialog>
    <Dialog open={Boolean(editUser)} onOpenChange={(open) => { if (!open) setEditUser(null); }}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Manage User</DialogTitle><DialogDescription>Update access for {editUser?.email}. Leave password blank to keep it unchanged.</DialogDescription></DialogHeader><UserForm form={form} setForm={setForm} teams={meta.teams} submitLabel="Save Changes" submitting={update.isPending} showActive active={editUser?.is_active} onActiveChange={(active) => update.mutate({ isActive: active })} onSubmit={() => update.mutate({ fullName: form.fullName, role: form.role, teamId: form.teamId || null, password: form.password || undefined, permissions: form.permissions })} /></DialogContent></Dialog>
  </div>;
}

function UserForm({ form, setForm, teams, submitLabel, submitting, onSubmit, showActive, active, onActiveChange }: { form: typeof emptyForm; setForm: Dispatch<SetStateAction<typeof emptyForm>>; teams: Array<{ id: string; name: string }>; submitLabel: string; submitting: boolean; onSubmit: () => void; showActive?: boolean; active?: boolean; onActiveChange?: (active: boolean) => void }) {
  const togglePermission = (permission: string) => setForm((value) => ({ ...value, permissions: value.permissions.includes(permission) ? value.permissions.filter((item) => item !== permission) : [...value.permissions, permission] }));
  return <form onSubmit={(event) => { event.preventDefault(); onSubmit(); }} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Name<input required value={form.fullName} onChange={(event) => setForm((value) => ({ ...value, fullName: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 px-3" /></label><label className="text-sm font-medium">Email<input required disabled={showActive} type="email" value={form.email} onChange={(event) => setForm((value) => ({ ...value, email: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 px-3 disabled:bg-slate-100" /></label><label className="text-sm font-medium">User Type<select value={form.role} onChange={(event) => setForm((value) => ({ ...value, role: event.target.value as CRMRole }))} className="mt-1 h-10 w-full border border-slate-300 bg-white px-3">{roles.map((role) => <option key={role.value} value={role.value}>{role.label}</option>)}</select></label><label className="text-sm font-medium">Team<select value={form.teamId} onChange={(event) => setForm((value) => ({ ...value, teamId: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 bg-white px-3"><option value="">No team</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label className="text-sm font-medium sm:col-span-2">{showActive ? 'New Password (optional)' : 'Temporary Password (optional)'}<input type="password" minLength={8} value={form.password} onChange={(event) => setForm((value) => ({ ...value, password: event.target.value }))} className="mt-1 h-10 w-full border border-slate-300 px-3" placeholder={showActive ? 'Leave blank to keep current password' : 'Leave blank to generate a secure password'} /></label></div><fieldset><legend className="mb-2 text-sm font-medium">Module Permissions</legend><div className="grid gap-2 border border-slate-200 p-3 sm:grid-cols-2">{permissions.map(([value, label]) => <label key={value} className="flex items-center gap-2 p-1 text-sm"><input type="checkbox" checked={form.permissions.includes(value)} onChange={() => togglePermission(value)} />{label}</label>)}</div></fieldset><div className="flex flex-wrap items-center justify-between gap-3">{showActive && <button type="button" onClick={() => onActiveChange?.(!active)} className={cn('h-9 border px-4 text-sm font-medium', active ? 'border-red-300 text-red-700' : 'border-emerald-300 text-emerald-700')}>{active ? 'Deactivate User' : 'Activate User'}</button>}<button disabled={submitting} className="ml-auto h-9 bg-blue-600 px-5 text-sm font-medium text-white disabled:opacity-50">{submitting ? 'Saving...' : submitLabel}</button></div></form>;
}
